# Generated by Django 4.2.1 on 2023-07-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="connexion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("Tel", models.CharField(max_length=50)),
                ("confirmationmdp", models.CharField(max_length=8)),
                ("motdepasse", models.CharField(max_length=8)),
            ],
        ),
    ]
